return {
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "gopls",
        "pyright",
        "rust-analyzer",
        "lua-language-server",
        "r-languageserver",
        "dockerfile-language-server",
        "terraform-ls",
        "gofumpt",
        "goimports",
        "gopls",
        "hadolint",
        "json-lsp",
        "lua-language-server",
        "luacheck",
        "markdownlint-cli2",
        "pyright",
        "ruff",
        "rust-analyzer",
        "shfmt",
        "stylua",
        "terraform-ls",
        "tflint",
        "bash-debug-adapter",
        "beautysh",
        "shellcheck",
        "bash-language-server",
        "nixpkgs-fmt",
        "nixfmt",
        "sqlfluff",
      },
    },
  },
}
